export const data =[
  {
    id: 1,
    title: "Disney World",
    location: "Orlando, Florida",
    googleMapsUrl: "https://www.google.com/maps/place/Walt+Disney+World%C2%AE+Resort/@28.3836154,-81.5452147,13.46z/data=!4m5!3m4!1s0x88dd7ee634caa5f7:0xa71e391fd01cf1a0!8m2!3d28.3771857!4d-81.57074",
    startDate: "17 Sep, 2021",
    endDate: "25 Sep, 2021",
    description: "Trip to Disney World with friends in September 2021. We spent a week in Disney World staying at Kidani Village at the Animal Kingdom Lodge.",
    image: "animalkingdom-cropped.png",
  },
  // {
  //   id: 2,
  //   title: "",
  //   location: "",
  //   googleMapsUrl: "",
  //   startDate: "",
  //   endDate: "",
  //   description: "",
  //   image: " ",
  // },
  // {
  //   id: 3,
  //   title: "",
  //   location: "",
  //   googleMapsUrl: "",
  //   startDate: "",
  //   endDate: "",
  //   description: "",
  //   image: " ",
  // },
  // {
  //   id: 4,
  //   title: "",
  //   location: "",
  //   googleMapsUrl: "",
  //   startDate: "",
  //   endDate: "",
  //   description: "",
  //   image: " ",
  // },
  // {
  //   id: 5,
  //   title: "",
  //   location: "",
  //   googleMapsUrl: "",
  //   startDate: "",
  //   endDate: "",
  //   description: "",
  //   image: " ",
  // }
]